// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sxghauouiuzuabfcslgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN4Z2hhdW91aXV6dWFiZmNzbGdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDA4MTgsImV4cCI6MjA3MTI3NjgxOH0.pJemi58GS0Kv2_4diDahAoBDqV7rRCJX2fGa-xJrzMs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});